/**
 * Diagram export: SVG, PNG and PDF.
 *
 * All three start from the same SVG string, so what you export is exactly what
 * the diagram shows. Everything happens in the browser — a schema diagram is a
 * picture of your database, and it never leaves the page.
 *
 * PDF uses `pdf-lib`, which the project already carries for the file toolkit,
 * rather than adding a second PDF library.
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const BACKGROUNDS = [
  { id: "theme", label: "Current theme", color: "#050505" },
  { id: "white", label: "White", color: "#ffffff" },
  { id: "transparent", label: "Transparent", color: null },
];

/** Swaps the background rect in a generated SVG for the chosen option. */
export function withBackground(svg, background) {
  const entry = BACKGROUNDS.find((option) => option.id === background) || BACKGROUNDS[0];
  // The generator always emits the ground as the first <rect data-role="bg">.
  if (entry.color === null) {
    return svg.replace(/<rect data-role="bg"[^>]*\/>/, "");
  }
  return svg.replace(
    /(<rect data-role="bg"[^>]*?fill=")[^"]*(")/,
    `$1${entry.color}$2`,
  );
}

/**
 * Rasterises an SVG string at `scale`.
 *
 * The SVG is handed to the decoder as a blob URL rather than a `data:` URI:
 * data URIs break on the non-ASCII characters that appear in field names and
 * labels, and a blob keeps the image same-origin so the canvas stays untainted.
 */
export async function svgToCanvas(svg, { scale = 2, background = "theme" } = {}) {
  const prepared = withBackground(svg, background);
  const sizeMatch = /viewBox="0 0 ([\d.]+) ([\d.]+)"/.exec(prepared);
  const width = Number(sizeMatch?.[1] || 1200);
  const height = Number(sizeMatch?.[2] || 800);

  const blob = new Blob([prepared], { type: "image/svg+xml;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  try {
    const image = new Image();
    await new Promise((resolve, reject) => {
      image.onload = resolve;
      image.onerror = () => reject(new Error("The diagram could not be rasterised."));
      image.src = url;
    });

    const canvas = document.createElement("canvas");
    canvas.width = Math.max(1, Math.round(width * scale));
    canvas.height = Math.max(1, Math.round(height * scale));
    const context = canvas.getContext("2d");

    const entry = BACKGROUNDS.find((option) => option.id === background);
    if (entry?.color) {
      context.fillStyle = entry.color;
      context.fillRect(0, 0, canvas.width, canvas.height);
    }

    context.drawImage(image, 0, 0, canvas.width, canvas.height);
    return canvas;
  } finally {
    URL.revokeObjectURL(url);
  }
}

/** SVG string → downloadable blob. Vector, so no scale to choose. */
export function exportSvg(svg, { background = "theme" } = {}) {
  return new Blob([withBackground(svg, background)], { type: "image/svg+xml;charset=utf-8" });
}

/** SVG → PNG at a chosen pixel density. */
export async function exportPng(svg, { scale = 2, background = "theme" } = {}) {
  const canvas = await svgToCanvas(svg, { scale, background });
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => (blob ? resolve(blob) : reject(new Error("This browser could not encode the PNG."))),
      "image/png",
    );
  });
}

const PAGE = {
  a4: { width: 595.28, height: 841.89, label: "A4" },
  a4landscape: { width: 841.89, height: 595.28, label: "A4 landscape" },
  a3landscape: { width: 1190.55, height: 841.89, label: "A3 landscape" },
  letter: { width: 612, height: 792, label: "Letter" },
};

export const PDF_PAGE_SIZES = Object.entries(PAGE).map(([id, entry]) => ({
  id,
  label: entry.label,
}));

/**
 * Builds a documentation-ready PDF: title block, metadata, then the diagram.
 *
 * A diagram wider than one page is tiled across pages rather than shrunk into
 * illegibility, with each tile labelled so the sheets can be laid out on a
 * desk in the right order.
 */
export async function exportPdf(
  svg,
  {
    title = "Prisma Schema Diagram",
    subtitle = "Generated by Devora",
    stats = null,
    pageSize = "a4landscape",
    background = "white",
    scale = 2,
    tileLargeDiagrams = true,
  } = {},
) {
  const page = PAGE[pageSize] || PAGE.a4landscape;
  const canvas = await svgToCanvas(svg, { scale, background: background === "transparent" ? "white" : background });

  const pdf = await PDFDocument.create();
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const regular = await pdf.embedFont(StandardFonts.Helvetica);

  const pngBlob = await new Promise((resolve) => canvas.toBlob(resolve, "image/png"));
  const embedded = await pdf.embedPng(await pngBlob.arrayBuffer());

  const margin = 42;
  const headerHeight = 96;
  const ink = rgb(0.05, 0.05, 0.05);
  const muted = rgb(0.42, 0.42, 0.45);
  const accent = rgb(1, 0.302, 0.11);

  /** Draws the title block, returning the y of the content area's top. */
  const drawHeader = (target, pageLabel) => {
    const top = page.height - margin;
    target.drawText(title, { x: margin, y: top - 18, size: 18, font: bold, color: ink });
    target.drawText(subtitle, { x: margin, y: top - 36, size: 10, font: regular, color: muted });
    target.drawLine({
      start: { x: margin, y: top - 48 },
      end: { x: page.width - margin, y: top - 48 },
      thickness: 1.5,
      color: accent,
    });

    if (stats) {
      const line = [
        `Models: ${stats.models}`,
        `Relations: ${stats.relations}`,
        stats.enums ? `Enums: ${stats.enums}` : null,
        `Fields: ${stats.fields}`,
        `Generated: ${new Date().toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}`,
      ]
        .filter(Boolean)
        .join("   ·   ");
      target.drawText(line, { x: margin, y: top - 66, size: 9, font: regular, color: muted });
    }

    if (pageLabel) {
      const labelWidth = regular.widthOfTextAtSize(pageLabel, 9);
      target.drawText(pageLabel, {
        x: page.width - margin - labelWidth,
        y: top - 66,
        size: 9,
        font: regular,
        color: muted,
      });
    }

    return page.height - margin - headerHeight;
  };

  const contentWidth = page.width - margin * 2;
  const contentHeight = page.height - margin - headerHeight - margin;
  const aspect = canvas.width / canvas.height;

  // How large the diagram would be if scaled to fit one page's width.
  const fitWidth = contentWidth;
  const fitHeight = fitWidth / aspect;

  /*
   * Tiling is a last resort, not the first response to any overflow.
   *
   * A diagram that is a little too tall should simply be scaled down — that
   * stays readable and keeps the document to one sheet. Only when fitting it
   * to a single page would shrink it past the point of legibility is it worth
   * splitting across sheets. 0.55 is roughly where 11px field labels stop
   * being comfortable in print.
   */
  const singlePageScale = Math.min(1, contentHeight / fitHeight);
  const needsTiling = tileLargeDiagrams && singlePageScale < 0.55;

  if (!needsTiling) {
    const target = pdf.addPage([page.width, page.height]);
    const contentTop = drawHeader(target, null);

    const drawWidth = fitHeight > contentHeight ? contentHeight * aspect : fitWidth;
    const drawHeight = drawWidth / aspect;

    target.drawImage(embedded, {
      x: margin + (contentWidth - drawWidth) / 2,
      y: contentTop - drawHeight,
      width: drawWidth,
      height: drawHeight,
    });
  } else {
    // Tile vertically: each page shows a horizontal band of the diagram at a
    // readable scale, rather than one page of unreadable thumbnail.
    const bandHeightPx = (canvas.width / contentWidth) * contentHeight;
    const bands = Math.ceil(canvas.height / bandHeightPx);

    for (let index = 0; index < bands; index += 1) {
      const target = pdf.addPage([page.width, page.height]);
      const contentTop = drawHeader(target, `Sheet ${index + 1} of ${bands}`);

      // Crop by drawing the full image clipped to the band via a slice canvas.
      const slice = document.createElement("canvas");
      slice.width = canvas.width;
      slice.height = Math.min(bandHeightPx, canvas.height - index * bandHeightPx);
      const context = slice.getContext("2d");
      if (background !== "transparent") {
        context.fillStyle = background === "white" ? "#ffffff" : "#050505";
        context.fillRect(0, 0, slice.width, slice.height);
      }
      context.drawImage(canvas, 0, -index * bandHeightPx);

      const sliceBlob = await new Promise((resolve) => slice.toBlob(resolve, "image/png"));
      const sliceImage = await pdf.embedPng(await sliceBlob.arrayBuffer());

      const drawHeight = (slice.height / canvas.width) * contentWidth;
      target.drawImage(sliceImage, {
        x: margin,
        y: contentTop - drawHeight,
        width: contentWidth,
        height: drawHeight,
      });
    }
  }

  pdf.setTitle(title);
  pdf.setProducer("Creates.io");
  pdf.setCreationDate(new Date());

  return new Blob([await pdf.save()], { type: "application/pdf" });
}
